name: API Test Automation

on:
  push:
    branches: [ main ]

jobs:
  run_and_upload_reports:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Maven Tests
        run: mvn clean test

      # This is the corrected step that uploads the ExtentReports report.
      - name: Upload ExtentReports Report
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report
          path: target/test-output/ExtentReport.html

      # This is the step that uploads the Allure results.
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-results

  allure_report:
    runs-on: ubuntu-latest
    needs: run_and_upload_reports # This job will run only after the 'run_and_upload_reports' job is complete
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-results

      - name: Generate Allure Report
        uses: allure-report/github-action@v2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allure_results: allure-results
          report_dir: allure-report
          github_pages: true