name: API Test Automation CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # This job runs the FULL regression suite and creates the report data
  build_and_test_regression:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Full Regression Suite
        run: mvn clean test -Dgroups=regression
      - name: Upload ExtentReports Report (Regression)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report-Regression
          path: target/ExtentReport.html
      - name: Upload Allure Results (Raw Data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results-Regression
          path: target/allure-results

  # This job runs a quick smoke test in parallel
  run_smoke_tests:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Smoke Test Suite
        run: mvn clean test -Dgroups=smoke
      - name: Upload ExtentReports Report (Smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report-Smoke
          path: target/ExtentReport.html

  # THIS JOB IS NOW CORRECTED
  # It generates the report and pushes it to the gh-pages branch
  generate_and_deploy_report:
    runs-on: ubuntu-latest
    needs: build_and_test_regression
    permissions:
      contents: write # Required to push to the gh-pages branch
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results-Regression
          path: allure-results

      - name: Build Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          # This creates the report in a folder named 'allure-history'
          allure_history: allure-history

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This is the folder that gets deployed
          publish_dir: ./allure-history