name: API Test Automation CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # This job runs the FULL regression suite and creates the report data
  build_and_test_regression:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Full Regression Suite
        run: mvn clean test -Dgroups=regression
      - name: Upload ExtentReports Report (Regression)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report-Regression
          path: target/ExtentReport.html
      - name: Upload Allure Results (Raw Data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results-Regression
          path: allure-results

  # This job runs a quick smoke test in parallel
  run_smoke_tests:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Smoke Test Suite
        run: mvn clean test -Dgroups=smoke
      - name: Upload ExtentReports Report (Smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report-Smoke
          path: target/ExtentReport.html

  generate_and_deploy_report:
    runs-on: ubuntu-latest
    needs: [build_and_test_regression, run_smoke_tests]
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Download Allure Results from Regression
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results-Regression
          path: allure-results

      - name: Download Allure Results from Smoke
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results-Smoke
          path: allure-results

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          name: Allure-Report
          path: target/allure-report