name: API Test Automation

on:
  push:
    branches: [ main ]

jobs:
  run_symbol_tests:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Symbol Search Tests
        run: mvn test -Dtest=SymbolSearchTests

  run_time_series_tests:
    runs-on: ubuntu-latest
    needs: run_symbol_tests
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Wait for API Rate Limit Reset
        run: sleep 15 # Wait for 15 seconds to ensure the rate limit has reset
      - name: Run Time Series Tests
        run: mvn test -Dtest=TimeSeriesTests