name: API Test Automation

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Tests
        run: mvn clean test

      # This is the corrected step that uploads the ExtentReports report as a downloadable artifact.
      - name: Upload ExtentReports Report
        uses: actions/upload-artifact@v5  # Corrected to use v4 or later
        with:
          name: ExtentReports-Report
          path: target/surefire-reports/ExtentReport.html