# This is the name of our workflow, which will appear in GitHub's "Actions" tab
name: API Test Automation

on:
  push:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Symbol Search Tests
        run: mvn test -Dtest=SymbolSearchTests

      - name: Wait to Avoid API Rate Limit
        run: sleep 60 # Wait for 60 seconds to reset the API's rate limit

      - name: Run Time Series Tests
        run: mvn test -Dtest=TimeSeriesTests