name: API Test Automation CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_symbol_tests:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Symbol Search Tests
        run: mvn clean test -Dgroups=regression

      - name: Upload ExtentReports Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report
          path: target/ExtentReport.html

      - name: Upload Allure Results (Raw Data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results
          path: allure-results

  run_time_series_tests:
    runs-on: ubuntu-latest
    needs: run_symbol_tests
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Wait for API Rate Limit Reset
        run: sleep 60 # Wait for 60 seconds to ensure the rate limit has reset
      - name: Run Time Series Tests
        run: mvn test -Dgroups=smoke

      - name: Upload ExtentReports Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report
          path: target/ExtentReport.html

      - name: Upload Allure Results (Raw Data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results
          path: allure-results

  allure_report:
    runs-on: ubuntu-latest
    needs: [run_symbol_tests, run_time_series_tests]
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download Allure Results from Regression
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results
          path: allure-results

      - name: Download Allure Results from Smoke
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results
          path: allure-results

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          name: Allure-Report
          path: target/allure-report