# .github/workflows/ci.yml

name: API Test Automation CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Maven Tests
        run: mvn clean test
      - name: Upload ExtentReports Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report
          path: target/extent-report.html
      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results
          path: target/allure-results

  generate_allure_report:
    runs-on: ubuntu-latest
    needs: build_and_test
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results
          path: allure-results

      # THIS IS THE ONLY STEP NEEDED FOR THE REPORT JOB
      # It generates the report AND deploys it to the 'gh-pages' branch
      - name: Generate and Deploy Allure Report to GitHub Pages
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report