# This is the name of our workflow, which will appear in GitHub's "Actions" tab
name: API Test Automation

# This tells GitHub when to run this workflow.
# 'push' means it will run every time you push code to the repository.
on: [push]

# A workflow is made up of one or more jobs.
jobs:
  # This is the name of our job
  build_and_test:
    # This specifies the environment where the job will run.
    # 'ubuntu-latest' is a standard, pre-configured virtual machine hosted by GitHub.
    runs-on: ubuntu-latest

    # The 'env' section defines environment variables for the job.
    # We are setting the API key from the secret we just created.
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}

    # The 'steps' section is a list of commands and actions to be executed.
    steps:
      # Action 1: This is a reusable action that checks out a copy of your repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Action 2: This action sets up the correct Java environment for us
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # Action 3: This action runs our Maven command.
      - name: Run Maven Tests
        run: mvn clean test