name: API Test Automation CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # AMENDMENT 1 & 2: Renamed job that now runs only the REGRESSION tests
  build_and_test_regression:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Full Regression Suite
        run: mvn clean test -Dgroups=regression
      - name: Upload ExtentReports Report (Regression)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport-Report-Regression
          path: target/ExtentReport.html
      - name: Upload Allure Results (Regression)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results-Regression
          path: target/allure-results

  # AMENDMENT 3: The completely new job for SMOKE tests
  run_smoke_tests:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run Smoke Test Suite
        run: mvn clean test -Dgroups=smoke
      - name: Upload ExtentReports Report (Smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport-Report-Smoke
          path: target/ExtentReport.html

  # AMENDMENT 4: The deployment job, now correctly depending on the regression run
  generate_allure_report_deployment:
    runs-on: ubuntu-latest
    needs: build_and_test_regression
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Download Allure Results
        uses: actions/download-artifact@v4
        with:
          name: Allure-Results-Regression
          path: allure-results
      - name: Generate and Deploy Allure Report
        uses: simple-elf/allure-report-action@v1.7
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4