# This is the name of our workflow, which will appear in GitHub's "Actions" tab
name: API Test Automation

# This tells GitHub when to run this workflow.
on: [push]

# A workflow is made up of one or more jobs.
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    # The 'env' section defines environment variables for the job.
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      # We can't use the 'pause' method from our BaseTest here.
      # Instead, we will add a separate job to run the tests one by one.
      - name: Run Symbol Search Tests
        run: mvn clean test -Dtest=SymbolSearchTests

      - name: Wait for API Rate Limit Reset
        run: sleep 60 # Wait for 60 seconds to reset the API's rate limit

      - name: Run Time Series Tests
        run: mvn test -Dtest=TimeSeriesTests