name: API Test Automation CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_and_deploy_reports:
    runs-on: ubuntu-latest
    env:
      ALPHAVANTAGE_API_KEY: ${{ secrets.ALPHAVANTAGE_API_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'
      - name: Run All Tests
        run: mvn clean test

      - name: Upload ExtentReports Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReports-Report
          path: target/surefire-reports/ExtentReport.html

      - name: Upload Allure Results (Raw Data)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Results
          path: allure-results

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v1
        with:
          name: Allure-Report
          path: target/allure-report